name:                wasm-binary
version:             0.1.0.0
github:              "githubuser/wasm-binary"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

description:         Please see the README

library:
  source-dirs: src
  exposed-modules:
  - Lang.Wasm.BinaryParser
  - Lang.Wasm.BinaryUnparser
  ghc-options:
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings
  dependencies:
  - melude
  - id-containers
  - base >= 4.7 && < 5
  - bytestring >= 0.10 && < 0.11
  - attoparsec >= 0.13 && < 0.14
  - wasm-ast >= 0.1
  - vector >= 0.12 && < 0.13
  - containers >= 0.6 && < 0.7
  - mtl >= 2.2 && < 2.3
  - unordered-containers >= 0.2 && < 0.3

tests:
  wasm-binary-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - tasty >= 1.2 && < 1.3
    - tasty-hunit >= 0.10 && < 0.11
    - bytestring >= 0.10 && < 0.11
    - attoparsec >= 0.13 && < 0.14
    - wasm-ast >= 0.1
