name:                melude
version:             0.1.0.0
github:              "githubuser/melude"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

description:         Please see the README

library:
  source-dirs: src
  exposed-modules:
  - Melude
  - Data.Uninterpreted
  ghc-options:
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings
  dependencies:
  - base >= 4.7 && < 5
  - id-containers
  - mtl >= 2.2 && < 2.3
  - base-unicode-symbols >= 0.2 && < 0.3
  - lens >= 4.17.1 && < 4.17.2
  - containers >= 0.6 && < 0.6.1
  - transformers >= 0.5.6 && < 0.5.7
  - hashable >= 1.3 && < 1.4
  - unordered-containers >= 0.2 && < 0.3
  - time >= 1.8 && < 1.9
  - vector >= 0.11 && < 0.13
